In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/propertyfinder.csv", low_memory=False)

/var/folders/92/gj3xwkp1413556yc9c_8tr5c0000gn/T/ipykernel_80973/1113400111.py:1: DtypeWarning: Columns (0: completion_status) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/propertyfinder.csv")

In [3]:
df = df.drop_duplicates()
df

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,...,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,56009081.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,24500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.012018e+11,2.022126e+10,pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,56247925.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,5145000.0,...,False,NaN,492.0,Abrag Real Estate,snawara71@gmail.com,2.010012e+11,2.010072e+11,2.022126e+10,ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,56253883.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,10800000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,56250852.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,10500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.010701e+11,2.022126e+10,ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,55995764.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,19500000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,YQT77A2J44CPMV7H28J9V30ADR,8667639.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,"Furnished apartment for rent in Al Rehab, 250M",55000.0,...,False,NaN,4456.0,Escan Group,aahmdymagdy201070@gmail.com,2.011233e+11,2.011040e+11,2.022126e+10,atiasaad188@gmail.com,2026-03-05T00:43:04.172513
39709,8385GKAA00BXE8FYPWNQ29VF3M,8667632.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,FULLY FURNISHED apartment for RENT 3 Bedroom,45000.0,...,False,NaN,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010947e+11,2.022126e+10,yuliya.hassan@remax.com.eg,2026-03-05T00:43:04.172513
39710,R9PTSC3V5RZ77ZT9X69TBE1PEC,8667625.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/town...,Townhouse,Residential for Rent,NaN,Furnished villa for rent in Town 5 rooms near New,120000.0,...,False,NaN,4679.0,Abrag 2,NaN,NaN,2.011146e+11,2.022126e+10,Mahmoudalabasy94@gmail.com,2026-03-05T00:43:04.172513
39711,9Q295E8B6ET3V30Z31925BR6ZG,8667615.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,For Rent – Premium 196m² Fully Finished Apartment,50000.0,...,False,NaN,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010707e+11,2.022126e+10,yalashwat2000@gmail.com,2026-03-05T00:43:04.172513
39712,HYEPN5XPWQT7K05K4ST7EDWW5R,8667602.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,NaN,If you're looking hotel units contact us now,75000.0,...,False,English | Arabic,5307.0,Smart Home,ahmedbompo9@gmail.com,2.010120e+11,2.010408e+11,2.022126e+10,sh2927333@gmail.com,2026-03-05T00:43:04.172513

In [4]:
df = df.ffill()
df

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,...,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,56009081.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,24500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.012018e+11,2.022126e+10,pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,56247925.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,5145000.0,...,False,NaN,492.0,Abrag Real Estate,snawara71@gmail.com,2.010012e+11,2.010072e+11,2.022126e+10,ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,56253883.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,10800000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,56250852.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,10500000.0,...,False,English | Arabic,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.010701e+11,2.022126e+10,ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,55995764.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,19500000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39708,YQT77A2J44CPMV7H28J9V30ADR,8667639.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,completed,"Furnished apartment for rent in Al Rehab, 250M",55000.0,...,False,English | Arabic,4456.0,Escan Group,aahmdymagdy201070@gmail.com,2.011233e+11,2.011040e+11,2.022126e+10,atiasaad188@gmail.com,2026-03-05T00:43:04.172513
39709,8385GKAA00BXE8FYPWNQ29VF3M,8667632.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,completed,FULLY FURNISHED apartment for RENT 3 Bedroom,45000.0,...,False,English | Arabic,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010947e+11,2.022126e+10,yuliya.hassan@remax.com.eg,2026-03-05T00:43:04.172513
39710,R9PTSC3V5RZ77ZT9X69TBE1PEC,8667625.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/town...,Townhouse,Residential for Rent,completed,Furnished villa for rent in Town 5 rooms near New,120000.0,...,False,English | Arabic,4679.0,Abrag 2,m.degheady@remax.com.eg,2.010308e+11,2.011146e+11,2.022126e+10,Mahmoudalabasy94@gmail.com,2026-03-05T00:43:04.172513
39711,9Q295E8B6ET3V30Z31925BR6ZG,8667615.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,completed,For Rent – Premium 196m² Fully Finished Apartment,50000.0,...,False,English | Arabic,430.0,RE/MAX Al Mohager,m.degheady@remax.com.eg,2.010308e+11,2.010707e+11,2.022126e+10,yalashwat2000@gmail.com,2026-03-05T00:43:04.172513
39712,HYEPN5XPWQT7K05K4ST7EDWW5R,8667602.0,rent,property,https://www.propertyfinder.eg/en/plp/rent/apar...,Apartment,Residential for Rent,completed,If you're looking hotel units contact us now,75000.0,...,False,English | Arabic,5307.0,Smart Home,ahmedbompo9@gmail.com,2.010120e+11,2.010408e+11,2.022126e+10,sh2927333@gmail.com,2026-03-05T00:43:04.172513

In [5]:
df.columns = df.columns.str.lower().str.strip()

In [6]:
if 'price' in df.columns:

    df['price'] = df['price'].replace('[₹,]', '', regex=True).astype(float)

In [7]:
df.to_csv("../data/processed/cleaned_data.csv", index=False)

In [8]:
df.head()

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,...,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,56009081.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,24500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.012018e+11,2.022126e+10,pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,56247925.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,5145000.0,...,False,NaN,492.0,Abrag Real Estate,snawara71@gmail.com,2.010012e+11,2.010072e+11,2.022126e+10,ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,56253883.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,10800000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,56250852.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,10500000.0,...,False,English | Arabic,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.010701e+11,2.022126e+10,ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,55995764.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,19500000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007